In [7]:
import pandas as pd

In [8]:
import numpy as np

In [9]:
df = pd.read_csv('Churn_Modelling.csv')

In [10]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [11]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [12]:
df.tail(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [15]:
#Describe the statistical information of numerical column
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [16]:
#PRint all columns
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [18]:
#print all rows
df.T

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
RowNumber,1,2,3,4,5,6,7,8,9,10,...,9991,9992,9993,9994,9995,9996,9997,9998,9999,10000
CustomerId,15634602,15647311,15619304,15701354,15737888,15574012,15592531,15656148,15792365,15592389,...,15798964,15769959,15657105,15569266,15719294,15606229,15569892,15584532,15682355,15628319
Surname,Hargrave,Hill,Onio,Boni,Mitchell,Chu,Bartlett,Obinna,He,H?,...,Nkemakonam,Ajuluchukwu,Chukwualuka,Rahman,Wood,Obijiaku,Johnstone,Liu,Sabbatini,Walker
CreditScore,619,608,502,699,850,645,822,376,501,684,...,714,597,726,644,800,771,516,709,772,792
Geography,France,Spain,France,France,Spain,Spain,France,Germany,France,France,...,Germany,France,Spain,France,France,France,France,France,Germany,France
Gender,Female,Female,Female,Female,Female,Male,Male,Female,Male,Male,...,Male,Female,Male,Male,Female,Male,Male,Female,Male,Female
Age,42,41,42,39,43,44,50,29,44,27,...,33,53,36,28,29,39,35,36,42,28
Tenure,2,1,8,1,2,8,7,4,4,2,...,3,4,2,7,2,5,10,7,3,4
Balance,0.0,83807.86,159660.8,0.0,125510.82,113755.78,0.0,115046.74,142051.07,134603.88,...,35016.6,88381.21,0.0,155060.41,0.0,0.0,57369.61,0.0,75075.31,130142.79
NumOfProducts,1,1,3,2,1,2,2,4,2,1,...,1,1,1,1,2,2,1,1,2,1
HasCrCard,1,0,1,0,1,1,1,1,0,1,...,1,1,1,1,0,1,1,0,1,1
IsActiveMember,1,1,0,0,1,0,1,0,1,1,...,0,0,0,0,0,0,1,1,0,0
EstimatedSalary,101348.88,112542.58,113931.57,93826.63,79084.1,149756.71,10062.8,119346.88,74940.5,71725.73,...,53667.08,69384.71,195192.4,29179.52,167773.55,96270.64,101699.77,42085.58,92888.52,38190.78
Exited,1,0,1,0,0,1,0,1,0,0,...,0,1,0,0,0,0,0,1,1,0

In [19]:
#Sort your dataframe based on age 
df.sort_values('Age')

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
3512,3513,15657779,Boylan,806,Spain,Male,18,3,0.00,2,1,1,86994.54,0
1678,1679,15569178,Kharlamov,570,France,Female,18,4,82767.42,1,1,0,71811.90,0
3517,3518,15757821,Burgess,771,Spain,Male,18,1,0.00,2,0,0,41542.95,0
9520,9521,15673180,Onyekaozulu,727,Germany,Female,18,2,93816.70,2,1,0,126172.11,0
2021,2022,15795519,Vasiliev,716,Germany,Female,18,3,128743.80,1,0,0,197322.13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3387,3388,15798024,Lori,537,Germany,Male,84,8,92242.34,1,1,1,186235.98,0
3033,3034,15578006,Yao,787,France,Female,85,10,0.00,2,1,1,116537.96,0
2458,2459,15813303,Rearick,513,Spain,Male,88,10,0.00,2,1,1,52952.24,0
6759,6760,15660878,T'ien,705,France,Male,92,1,126076.24,2,1,1,34436.83,0
6443,6444,15764927,Rogova,753,France,Male,92,3,121513.31,1,0,1,195563.99,0

In [20]:
new_df = df.sort_values('Age')

In [22]:
new_df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
3512,3513,15657779,Boylan,806,Spain,Male,18,3,0.00,2,1,1,86994.54,0
1678,1679,15569178,Kharlamov,570,France,Female,18,4,82767.42,1,1,0,71811.90,0
3517,3518,15757821,Burgess,771,Spain,Male,18,1,0.00,2,0,0,41542.95,0
9520,9521,15673180,Onyekaozulu,727,Germany,Female,18,2,93816.70,2,1,0,126172.11,0
2021,2022,15795519,Vasiliev,716,Germany,Female,18,3,128743.80,1,0,0,197322.13,0

In [23]:
df['Balance']

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [24]:
df['Balance'] + 1000

0         1000.00
1        84807.86
2       160660.80
3         1000.00
4       126510.82
          ...
9995      1000.00
9996     58369.61
9997      1000.00
9998     76075.31
9999    131142.79
Name: Balance, Length: 10000, dtype: float64

In [25]:
#how to access rows 

df[10:12]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
10,11,15767821,Bearce,528,France,Male,31,6,102016.72,2,0,0,80181.12,0
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0

In [28]:
age_50 = df[df.Age >50]

In [30]:
age_50

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1
41,42,15738148,Clarke,465,France,Female,51,8,122522.32,1,0,0,181297.65,1
42,43,15687946,Osborne,556,France,Female,61,2,117419.35,1,1,1,94153.83,0
44,45,15684171,Bianchi,660,Spain,Female,61,5,155931.11,1,1,1,158338.39,0
58,59,15623944,T'ien,511,Spain,Female,66,4,0.00,1,1,0,1643.11,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9936,9937,15653037,Parks,609,France,Male,77,1,0.00,1,0,1,18708.76,0
9939,9940,15808971,Lajoie,693,Spain,Female,57,9,0.00,2,1,1,135502.77,0
9948,9949,15735078,Onwughara,724,Germany,Female,53,1,139687.66,2,1,1,12913.92,0
9979,9980,15692664,Diribe,677,France,Female,58,1,90022.85,1,0,1,2988.28,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1

In [31]:
df['Age'].fillna(15)

0       42
1       41
2       42
3       39
4       43
        ..
9995    39
9996    35
9997    36
9998    42
9999    28
Name: Age, Length: 10000, dtype: int64

In [33]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 3512 to 6443
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [39]:
#REmove columns
new_df.pop('RowNumber')
# or new_df.drop('RowNumber', axis=1)

In [38]:
new_df

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
3512,15657779,Boylan,806,Spain,Male,18,3,0.00,2,1,1,86994.54,0
1678,15569178,Kharlamov,570,France,Female,18,4,82767.42,1,1,0,71811.90,0
3517,15757821,Burgess,771,Spain,Male,18,1,0.00,2,0,0,41542.95,0
9520,15673180,Onyekaozulu,727,Germany,Female,18,2,93816.70,2,1,0,126172.11,0
2021,15795519,Vasiliev,716,Germany,Female,18,3,128743.80,1,0,0,197322.13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3387,15798024,Lori,537,Germany,Male,84,8,92242.34,1,1,1,186235.98,0
3033,15578006,Yao,787,France,Female,85,10,0.00,2,1,1,116537.96,0
2458,15813303,Rearick,513,Spain,Male,88,10,0.00,2,1,1,52952.24,0
6759,15660878,T'ien,705,France,Male,92,1,126076.24,2,1,1,34436.83,0
6443,15764927,Rogova,753,France,Male,92,3,121513.31,1,0,1,195563.99,0

In [40]:
df['Balance']

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [41]:
df['Balance'].apply(np.sqrt)

0         0.000000
1       289.495872
2       399.575775
3         0.000000
4       354.275063
           ...
9995      0.000000
9996    239.519540
9997      0.000000
9998    273.998741
9999    360.753087
Name: Balance, Length: 10000, dtype: float64

In [42]:
#Drop all null values 
df.dropna()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
# Concat and Merging

In [43]:
import pandas as pd

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'], 
                    'B': ['B0', 'B1', 'B2', 'B3'], 
                    'C': ['C0', 'C1', 'C2', 'C3'], 
                    'D': ['D0', 'D1', 'D2', 'D3']}, 
                  index=[0,1,2,3])

In [44]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [46]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'], 
                    'B': ['B4', 'B5', 'B6', 'B7'], 
                    'C': ['C4', 'C5', 'C6', 'C7'], 
                    'D': ['D4', 'D5', 'D6', 'D7']}, 
                  index=[4,5,6,7])

In [47]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [48]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'], 
                    'B': ['B0', 'B1', 'B2', 'B3'], 
                    'C': ['C0', 'C1', 'C2', 'C3'], 
                    'D': ['D0', 'D1', 'D2', 'D3']}, )


df2 = pd.DataFrame({'E': ['A4', 'A5', 'A6', 'A7'], 
                    'F': ['B4', 'B5', 'B6', 'B7'], 
                    'C': ['C0', 'C3', 'C6', 'C7'], 
                    'G': ['D4', 'D5', 'D6', 'D7']}, )


merge_df = pd.merge(df1, df2, on='C', how='outer')

In [49]:
merge_df

     A    B   C    D    E    F    G
0   A0   B0  C0   D0   A4   B4   D4
1   A1   B1  C1   D1  NaN  NaN  NaN
2   A2   B2  C2   D2  NaN  NaN  NaN
3   A3   B3  C3   D3   A5   B5   D5
4  NaN  NaN  C6  NaN   A6   B6   D6
5  NaN  NaN  C7  NaN   A7   B7   D7

In [51]:
merge_df = pd.merge(df1, df2, on='C', how='left')

In [52]:
merge_df

    A   B   C   D    E    F    G
0  A0  B0  C0  D0   A4   B4   D4
1  A1  B1  C1  D1  NaN  NaN  NaN
2  A2  B2  C2  D2  NaN  NaN  NaN
3  A3  B3  C3  D3   A5   B5   D5

In [ ]:
#LOc and Iloc

In [54]:
s = pd.Series(list("abcdef"), index=[49,48,47,0,1,2])
s

49    a
48    b
47    c
0     d
1     e
2     f
dtype: object

In [55]:
s.loc[0]

'd'

In [58]:
s.iloc[3]

'd'

In [60]:
s.loc[0:1] #rows at index labels betqwqeen 0 and 1 (inclusive)

0    d
1    e
dtype: object

In [61]:
s.iloc[0:1] #rows at index labels betqwqeen 0 and 1 (enclusive)

49    a
dtype: object